# Site settings
title: The Programming Languages Laboratory
subtitle: at The Johns Hopkins University
email: pl.cs@jhu.edu
description: >
  The Programming Languages Laboratory at The Johns Hopkins University.
url: "https://pl.cs.jhu.edu" # the base hostname & protocol for your site
exclude:
  - README.md
  - Vagrantfile
  - bower.json
  - docker-compose.yml

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
sass:
  sass_dir: assets
  theme: lumen
